export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
export const USER_POST_STATE_CHANGE = 'USER_POST_STATE_CHANGE';
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE';

export const USERS_POST_STATE_CHANGE = 'USERS_POST_STATE_CHANGE';
export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE';
export const USERS_LIKES_STATE_CHANGE = 'USERS_LIKES_STATE_CHANGE';


export const USER_CHATS_STATE_CHANGE = 'USER_CHATS_STATE_CHANGE';
export const USER_MESSAGES_STATE_CHANGE = 'USER_MESSAGES_STATE_CHANGE';


export const CLEAR_DATA = 'CLEAR_DATA';